---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-password
  namespace: default
spec:
  encryptedData:
    password: AgAobPNGRnu2dhKTY6cdt9aZl7Kp44TQ5ZaUClcHx7cFEEg6VU6YZJm9ImN3LruFU0w7zBZQx4AQUISswmXGDBXyQ7gyrZK1RZ8EgxBBg+tvyGleZW5UBMo/b4jkN8Rwld9Y1qheM04Hh3ZSi91FR6SUqObgicTfLsg4Kmuu5YO2s7tma0UzRSVzXKH65WBzTG6nMvc/oNaMiZukcDfpqrUE+MpelmfbaFVk82nFJ3FiZMwTD9FkrTM737/G2h5jXglKeIe14fczl1l+16nlbBJZbnewiIFkoNbxuqzj+bTLYGd5KUC3f+Jd9JllpfnEMmLBk3T+er3RA3YCtJXgH3wld6Iqzz06jYS+Dj5FtUCaYH4n+rw4ATuTgD6R3FMt3sLnte5cQaS3xd2XfRVzkLdlEb199XYd73mYkfl05DFgZFl12QsuuiExkrL3eQ2JcWiDup3tIQe6jGsS156GAvgJfuujCVjwg3L5Db0C+0RcSagjt/+o/Yxy6nM4YtzFlH4IhlRf0gphjH20HQNJeZ79sftUl42Kg02o/Xeup7onzvZIxtlmKWurfBZq7Zr+YiyqvW80LrFT68MoAKdsB4sBbfkgnj/yWE1PitNohvtibx/mO1ZyhLAQv6PRe+TlbgzvNL4jVYhBc2EqJEzeLREHdKwYeJhgisqkLJ1Fmp2GbhrwxyEQqEZ0EIx3Iq+mlbLDusJ5/CgGo9M2yQWMO2uZ
  template:
    metadata:
      name: database-password
      namespace: default
